# Generated by Django 5.2.15 on 2026-06-20 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transcription', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transcript',
            name='has_edits',
            field=models.BooleanField(default=False),
        ),
    ]
