# Generated by Django 5.2.15 on 2026-06-12 17:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('uploads', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Summary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key_points', models.JSONField(default=list)),
                ('exam_flags', models.JSONField(default=list)),
                ('action_items', models.JSONField(default=list)),
                ('flashcards', models.JSONField(default=list)),
                ('summary_paragraph', models.TextField()),
                ('prompt_version', models.CharField(max_length=20)),
                ('starter_questions', models.JSONField(default=list)),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='summary', to='uploads.session')),
            ],
        ),
    ]
