# Generated by Django 5.2.15 on 2026-07-04 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summarisation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='summary',
            name='strict_exam_flags',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
