# Generated by Django 5.2.15 on 2026-06-12 17:54

import apps.uploads.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(default=apps.uploads.models.default_expires_at)),
                ('status', models.CharField(choices=[('uploading', 'Uploading'), ('transcribing', 'Transcribing'), ('summarising', 'Summarising'), ('complete', 'Complete'), ('failed', 'Failed')], default='uploading', max_length=20)),
                ('detected_language', models.CharField(blank=True, max_length=10)),
                ('duration_seconds', models.IntegerField(blank=True, null=True)),
                ('original_filename', models.CharField(max_length=255)),
                ('error_detail', models.TextField(blank=True)),
            ],
        ),
    ]
