# Generated by Django 5.2.15 on 2026-07-04 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='source_platform',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='session',
            name='source_url',
            field=models.URLField(blank=True, max_length=2048, null=True),
        ),
        migrations.AlterField(
            model_name='session',
            name='status',
            field=models.CharField(choices=[('initiated', 'Initiated'), ('fetching_metadata', 'Fetching Metadata'), ('downloading', 'Downloading'), ('uploading', 'Uploading'), ('transcribing', 'Transcribing'), ('summarising', 'Summarising'), ('complete', 'Complete'), ('failed', 'Failed')], default='uploading', max_length=20),
        ),
    ]
